### ISSUE TITLE
Key error when running filtercache on non Search diags

### ISSUE THREAD

**Issue by rssvihla** [DataStax-Toolkit/sperf#1]
sperf search filtercache doesn't handle non search tarballs correctly

```
sperf -v search filtercache -d ~/code/sperf/tests/testdata/diag/DSE_CLUSTER
sperf filtercache: 0.6.0

from directory '/Users/rsvihla/code/sperf/tests/testdata/diag/DSE_CLUSTER':
Traceback (most recent call last):
  File "sperf", line 13, in <module>
  File "pysper/commands/sperf.py", line 41, in run
  File "pysper/commands/sperf.py", line 38, in run
  File "pysper/commands/search/filtercache.py", line 37, in run
  File "pysper/search/filtercache.py", line 124, in parse
  File "pysper/search/filtercache.py", line 124, in <listcomp>
KeyError: 'date'
[47050] Failed to execute script sperf
```

**Comment by rssvihla** [comment]
Issue here is the same output but different scenario https://github.com/DataStax-Toolkit/sperf/issues/10
