### ISSUE TITLE
error running filter cache

### ISSUE THREAD

**Issue by rssvihla** [DataStax-Toolkit/sperf#10]
From Swapnil Bhisey (obfuscated logs and command for privacy)

```sperf -p --debug search filtercache -f node1/logs/cassandra/debug.log 
sperf filtercache: 0.6.0
from directory '.':
..Traceback (most recent call last):
  File "sperf", line 13, in <module>
  File "pysper/commands/sperf.py", line 41, in run
  File "pysper/commands/sperf.py", line 38, in run
  File "pysper/commands/search/filtercache.py", line 37, in run
  File "pysper/search/filtercache.py", line 124, in parse
  File "pysper/search/filtercache.py", line 124, in <listcomp>
KeyError: 'date'
[22473] Failed to execute script sperf```

Example Logs (time and data obfuscated)
```
INFO  [RemoteMessageServer query worker - 37] 2000-01-01 01:01:01,001  SolrFilterCache.java:375 - Filter cache org.apache.solr.search.SolrFilterCache$3@000000 has reached 1111111 entries of a maximum of 1111111. Evicting oldest entries...
INFO  [RemoteMessageServer query worker - 37] 2000-01-01 01:01:01,002  SolrFilterCache.java:391 - ...eviction completed in 4165 milliseconds. Filter cache org.apache.solr.search.SolrFilterCache$3@000000 usage is now 222222222 bytes across 22222222 entries.
```

**Comment by rssvihla** [comment]
Dupe of https://github.com/DataStax-Toolkit/sperf/issues/1 wont fix
