### ISSUE TITLE
Ignore archives when iterating for logs -> WAS: output of DSE 6.8.0 cluster with -t dse -m extended option gives error

### ISSUE THREAD

**Issue by msmygit** [DataStax-Toolkit/sperf#14]
Collected output of `DSE 6.8.0` cluster with [`-t dse -m extended`](https://github.com/datastax-toolkit/diagnostic-collection) option gives the following error when running `sperf` on it,
```
Traceback (most recent call last):
  File "sperf", line 13, in <module>
  File "pysper/commands/sperf.py", line 41, in run
  File "pysper/commands/sperf.py", line 38, in run
  File "pysper/commands/core/slowquery.py", line 30, in run
  File "pysper/commands/core/slowquery.py", line 38, in run_func
  File "pysper/core/slowquery.py", line 103, in print_report
  File "pysper/core/slowquery.py", line 77, in analyze
  File "pysper/core/slowquery.py", line 27, in parse
  File "/Users/travis/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 10: invalid start byte
[51115] Failed to execute script sperf
```

**Comment by foundev** [comment]
So having time to dig into this now, there is nothing going on with 6.8.0 specially and i think this is just a zip file it’s encountered and I can teach it to ignore. Will start doing this now

**Comment by foundev** [comment]
rolled this in with the #28  testing
