### ISSUE TITLE
invalid block_dev report file causes core diag to fail

### ISSUE THREAD

**Issue by arvy** [DataStax-Toolkit/sperf#7]
If blockdev_report file has invalid contents, such as

```
/sbin/blockdev --report
exit status: 1

stderr:
sudo: sorry, you must have a tty to run sudo
```

..the `core diag` command fails, due to failure in rendering the read-ahead setting in the report:

```
% sperf -v core diag
sperf core diag: 0.6.0

error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
error opening:  with [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "sperf", line 13, in <module>
  File "pysper/commands/sperf.py", line 41, in run
  File "pysper/commands/sperf.py", line 38, in run
  File "pysper/commands/core/diag.py", line 60, in run
  File "pysper/core/diag/__init__.py", line 16, in generate_report
  File "pysper/core/diag/reporter.py", line 27, in write_config
  File "pysper/core/diag/reporter.py", line 239, in _format_read_ahead
  File "pysper/humanize.py", line 64, in format_bytes
TypeError: '<' not supported between instances of 'NoneType' and 'int'
[29500] Failed to execute script sperf
```

It would be nice to add a defensive check [here](https://github.com/riptano/sperf/blob/0.6.0/pysper/core/diag/reporter.py#L27) and exclude RA from the report if it's undefined

**Comment by rssvihla** [comment]
Fixed in #8
